import sys
P='build_guide.py'
s=open(P).read()
R=[]
def rep(old,new):
    R.append((old,new))

# ---------- Q1 intro ----------
rep('<div class="eyebrow">Drawn · the machine, click a part</div>',
    '<div class="eyebrow">Drawing: the whole machine, with its four inputs on the left, the 64 neurons in the middle and the three outputs on the right. Click any part to read what it is.</div>')
rep('<div class="eyebrow">Real · run 19, how much each input is listened to</div>',
    '<div class="eyebrow">Real data: run 19, the average size of the weights from each input wire into the 64 neurons</div>')
rep('Averaging the size of those 64 weights per input tells you how loudly each input is heard. All four are used, and speed is heard slightly loudest. The output biases (the resting position of each output before any neuron speaks) tell the story of the erase gate: it started at −5 and, after five shifts and training, sits at +1.86.',
    'If we take the 64 weights belonging to one input wire, ignore their signs and average their sizes, we get one number that says how strongly that input is used by the network. The chart shows that number for each of the four inputs. All four are used, and the speed input is used slightly more than the others. The chart also shows the three output biases. A bias is the resting value of an output: the value it would have if no neuron were pushing on it at all. The erase gate\'s bias is the one to notice. It started at −5, and after five hand-made shifts and further training it now sits at +1.86. Question 3 explains why that journey mattered.')

# ---------- two kinds of number ----------
rep('<p>Before the arithmetic, the most important distinction in the machine. Some numbers are recomputed every tick. Others are looked up every tick but never change during a trip. Press the clock.</p>',
    '<p>Before we do any arithmetic, here is the most important distinction in the machine. Some of its numbers are recomputed on every tick. Other numbers are looked up on every tick but never change during a trip. Press the clock buttons below and watch which boxes flash.</p>')
rep('<div class="eyebrow">Drawn · press the clock and watch what moves</div>',
    '<div class="eyebrow">Drawing: the machine as a set of boxes; press the clock and see which boxes are recomputed</div>')
rep('<div class="how"><b>How to read it.</b> Boxes that flash are recomputed on every tick: the 64 activities, the three outputs, and the whole F table. Boxes with a padlock never change during a trip: W, A, W_in, W_out and ws. They were set by training, once. Every parameter you have heard of is a padlock box. Everything that carries a memory of this trip is a flashing box.</div>',
    '<div class="how"><b>How to read it.</b> Each box is one group of numbers inside the machine. When you press "advance one tick", the boxes that flash are the ones that get recomputed on that tick: the 64 activities, the three outputs, and the whole F table. The boxes marked with a padlock are the ones that never change during a trip: W, A, W_in, W_out and ws. Training set those numbers once, and after that they are frozen. Every parameter mentioned anywhere on this page is one of the padlock boxes. Anything that carries a memory of the current trip must be one of the flashing boxes, because those are the only numbers that change while the trip is happening.</div>')

# ---------- counting squares ----------
rep('<p>Where do 320, 195, 4,096 and 8,708 come from? Count squares. Every wire between two things has one weight, and every neuron or output has one bias, drawn as a strip on the side. Hover a square to name it.</p>',
    '<p>Where do the numbers 320, 195, 4,096 and 8,708 come from? You can get every one of them by counting squares in the drawing below. Every wire between two things has one weight, drawn as one square. Every neuron and every output also has one bias, drawn as a strip of squares along the side of its table. Hover over any square and the caption will tell you which number it is.</p>')
rep('<div class="eyebrow">Drawn · the five parameter tables, to scale, plus F</div>',
    '<div class="eyebrow">Drawing: the five parameter tables drawn to scale, one square per number, with the F table beside them</div>')
rep('ws: one square. Add them: 320 + 4,096 + 4,096 + 195 + 1 = 8,708 parameters. F is drawn greyed because it is the same size as W but not a parameter: it starts at zero every episode and the rule writes it.</div>',
    'ws: one square. Add them all up: 320 + 4,096 + 4,096 + 195 + 1 = 8,708 parameters. F is drawn in grey because, although it is the same size as W, it is not a parameter: it starts at zero at the beginning of every episode and the rule rewrites it on every tick, so training never sets it directly.</div>')

# ---------- two-strand wire ----------
rep('<div class="eyebrow">Drawn · a two-strand wire</div>',
    '<div class="eyebrow">Drawing: one connection as a wire with two strands, one permanent and one temporary</div>')

# ---------- W is the whole table ----------
rep('<h3>W is the whole table, not a summary of it</h3>\n<p>When the page says "W", it means all 4,096 cells together, the way "the spreadsheet" means every cell in it. W[i,j] is one cell. Nothing is averaged: the network needs every cell separately on every tick. Here is run 19\'s actual W, all of it, and beside it what a summary would be.</p>',
    '<h3>W means the whole table of 4,096 cells</h3>\n<p>When this page says "W", it means all 4,096 cells together, in the same way that "the spreadsheet" means every cell in a spreadsheet and not some total at the bottom. W[i,j] is one cell of that table. Nothing is averaged when the network runs: it needs every cell separately, on every tick. Below is run 19\'s actual W, all 4,096 cells, and beside it the A table drawn the same way.</p>')
rep('<div class="eyebrow">Real · run 19\'s W, all 4,096 cells, and its A</div>',
    '<div class="eyebrow">Real data: run 19\'s W, all 4,096 cells, with its A table drawn beside it</div>')
rep('<div class="how"><b>How to read it.</b> Row i, column j is the cell W[i,j]: how hard neuron j pushes neuron i. Red positive, blue negative, white near zero. This whole picture is what "W" means. A single summary number of it (the average, +0.00, or the mean size, 0.10) is written at the bottom, and it tells you almost nothing about how the network works, which is the point: the information is in the pattern of the cells, not in any total.</div>',
    '<div class="how"><b>How to read it.</b> Each small square is one cell of the table. The square in row i and column j is the cell W[i,j], which says how hard neuron j pushes neuron i. Red means a positive value (neuron j excites neuron i), blue means a negative value (neuron j quiets neuron i), and white means the value is near zero. This whole picture is what the word "W" refers to. Two summary numbers are written at the bottom of the picture: the average of all the cells (+0.00) and the average size of a cell ignoring its sign (0.10). Those summaries tell you almost nothing about how the network works. The reason is that the network\'s behaviour depends on the pattern of the cells, on which particular cells are positive and which are negative, and a single total cannot capture a pattern.</div>')
rep('<div class="eyebrow">Drawn · W is the wiring diagram, on a six-neuron version</div>',
    '<div class="eyebrow">Drawing: W as a wiring diagram, on a six-neuron version of the network</div>')
rep('Six neurons have 6 × 6 = 36 cells; ours has 64 × 64 = 4,096. That is all W is: the complete list of who listens to whom and how much, and it does not change during a trip. The activities are what each neuron is saying this tick; W is how much each neuron trusts each other neuron.</p>',
    'Six neurons have 6 × 6 = 36 cells; our network has 64 × 64 = 4,096. So W is nothing more than the complete list of who listens to whom and by how much, and that list does not change during a trip. It helps to keep two ideas apart here. The activities are what each neuron is saying on this tick, and they change every tick. W is how much each neuron trusts each other neuron, and it stays fixed for the whole trip.</p>')

# ---------- F board ----------
rep('<div class="eyebrow">Drawn · the F board, one tick in three moves</div>',
    '<div class="eyebrow">Drawing: a 4-by-4 corner of the F table, with one tick shown as three separate moves</div>')
rep('<small>Multiplier on the new deposit. 0 means the pen\'s cap is on.</small>',
    '<small>Multiplier on the new deposit. 0 means nothing at all is added this tick; 1 means the whole deposit is added.</small>')
rep('<button class="btn" id="fbTen">ten full ticks with the pen down (write 1, erase 0)</button>',
    '<button class="btn" id="fbTen">ten full ticks with write 1 and erase 0</button>')
rep('<div class="how"><b>Why (1 − erase) and not × erase.</b> The gate is named for what it removes. Erase 0.28 means 28% of each cell goes, 72% stays, and "keep 72%" is × (1 − 0.28). Multiplying by the gate directly would make erase = 1 keep everything, the word backwards. Either convention works mathematically (training would learn the opposite sign); this one makes "erase fires at food" read like the fly\'s reset. The LSTM\'s "forget gate" uses the other convention, which is why that name confuses people.</div>',
    '<div class="how"><b>Why the rule multiplies by (1 − erase) rather than by erase.</b> The erase gate is named for the amount it removes. An erase value of 0.28 means that 28% of each cell is removed, so 72% of it stays, and "keep 72%" is written as multiplying by (1 − 0.28) = 0.72. If the rule multiplied by the gate itself instead, then erase = 1 would keep everything, which is the opposite of what the word "erase" says. Either convention works mathematically, because training would simply learn the opposite sign for the gate. This convention was chosen so that the sentence "the erase gate fires at food" describes the fly\'s reset directly. The LSTM, a common kind of network with a built-in memory, has a "forget gate" that uses the other convention: there, forget = 1 means keep everything. That is why the name "forget gate" confuses people.</div>')
rep('<div class="how"><b>Why move 3 often changes nothing.</b> The clamp only touches cells already past +1 or −1. After one deposit on this board, none are, so nothing happens. Press "ten full ticks with the pen down" and watch cells climb until the clamp bites: clipped cells get an orange border and the count is written below. That is the lid from the Counter page, cell by cell.</div>',
    '<div class="how"><b>Why move 3 often changes nothing.</b> Move 3 is the clamp: any cell above +1 is set back to +1, and any cell below −1 is set back to −1. It only affects cells that are already past those limits. After a single deposit on this board no cell is past them, so move 3 does nothing. To see it act, press "ten full ticks with write 1 and erase 0". The cells climb tick by tick until some of them reach +1 or −1 and the clamp stops them. Cells that were clipped get an orange border, and the number of clipped cells is written underneath. This clipping is the same "lid" described on the Counter With a Lid page, here shown happening to one cell at a time.</div>')
rep('<div class="how"><b>How to read it.</b> Left: the 16 cells of F, colour and number. Middle: the deposit, which is the receiver\'s activity now times the sender\'s activity a tick ago, one product per cell (that is the "outer product"; four neurons here, the activities are shown along the edges). Right: the result. Move 1 multiplies every cell by the same (1 − erase). Move 2 adds ws × write × deposit. Move 3 clips anything past ±1. Then the board becomes the "before" for the next tick. Try erase at 0.77 and watch move 1 nearly empty the board: that is the reset.</div>',
    '<div class="how"><b>How to read it.</b> The left grid shows the 16 cells of F as they are at the start of the tick, each with its colour (red for positive, blue for negative) and its number. The middle grid shows the deposit. Each cell of the deposit is the receiving neuron\'s activity now multiplied by the sending neuron\'s activity one tick ago, so there is one product per cell. A table of all such products is called an "outer product". There are four neurons here, and their activities are written along the edges of the grid. The right grid shows the result of the tick. Move 1 multiplies every cell by the same number, (1 − erase). Move 2 adds ws × write × deposit to every cell. Move 3 clips anything past +1 or −1 back to those limits. After the three moves, the right grid becomes the "before" grid for the next tick. Try setting erase to 0.77, which is what run 19 does at food, and watch move 1 nearly empty the board. That emptying is the reset.</div>')

# ---------- one tick by hand ----------
rep('<div class="eyebrow">Drawn · one tick by hand, on a three-neuron version of the same machine</div>',
    '<div class="eyebrow">Drawing: one tick worked out by hand, on a three-neuron version of the same machine</div>')

# ---------- training ----------
rep('<p>Training never touches F or the activities. It touches the parameters, with one rule applied to every one of the 8,708 numbers after each batch of 32 episodes. First the picture, then the formula.</p>',
    '<p>Training never touches F or the activities. It changes only the parameters, and it does so with one rule applied to every one of the 8,708 numbers after each batch of 32 episodes. The rule needs two ideas. The <span class="term" title="loss: a single number that says how badly the network did on a batch of episodes; training tries to make it smaller">loss</span> is a single number that says how badly the network did on the batch, and lower is better. The <span class="term" title="learning rate: a fixed number that sets how big each adjustment to the parameters is">learning rate</span> is a fixed number that sets how big each adjustment is. The picture below shows the rule acting on a single parameter.</p>')
rep('<div class="eyebrow">Drawn · one parameter, one step downhill</div>',
    '<div class="eyebrow">Drawing: one parameter, moved one step downhill on the loss curve</div>')
rep('<small>Step size. The real runs used 0.001, 0.0003 and 0.0001; the hill here is drawn steep so steps are visible.</small>',
    '<small>The step size. The real runs used 0.001, 0.0003 and 0.0001. The curve here is drawn much steeper than a real one so that the steps are visible.</small>')
rep('<div class="how"><b>How to read it.</b> Across: the value of one parameter, say the erase bias. Up: the loss the network would get with that value (everything else fixed). The ball is the current value. Each step measures the slope under the ball and moves it downhill by learning rate × slope. On a steep part it moves a lot; on a flat part it barely moves, which is the deaf gate of question 3 seen from the other side. Turn the learning rate up to 1.0 and watch it overshoot and bounce: that is run 5\'s collapse.</div>',
    '<div class="how"><b>How to read it.</b> Across the bottom is the value of one parameter, for example the erase gate\'s bias. Up the side is the loss the network would get with that value, if every other parameter were held fixed. The black curve therefore shows how the loss changes as this one parameter changes. The ball marks the parameter\'s current value. Each time you press "one training step", the ball measures the slope of the curve directly underneath it and moves downhill by the learning rate multiplied by that slope. Where the curve is steep the ball moves a long way. Where the curve is nearly flat the ball barely moves at all, because the slope is close to zero. That flat-part behaviour is the same thing as the "deaf gate" of question 3, seen from the other side: a gate resting on a flat part of its own curve gives training a tiny slope to work with, so training barely moves it. Now try turning the learning rate up to 1.0. The ball overshoots the bottom of the valley and bounces from side to side instead of settling. That bouncing is what happened in run 5, where the loss suddenly got worse instead of better; the pages call this run 5\'s collapse.</div>')
rep('<p>A knob is any number or choice we fix <em>before</em> a run starts and hold fixed during it. It is not something the network learns. The 8,708 slow weights are learned, so they are not knobs. The fast weights F are rewritten by the network itself, so they are not knobs either. Everything else is. Here is the whole board, grouped by what part of the experiment it lives in. Click a knob to see what it does and which runs turned it.</p>',
    '<p>A knob is any number or choice that we fix <em>before</em> a run starts and hold fixed while it runs. A knob is never something the network learns. The 8,708 slow weights are learned by training, so they are not knobs. The fast weights F are rewritten by the network itself while it runs, so they are not knobs either. Every other number or choice that we fix beforehand is a knob. Here is the whole board of them, grouped by the part of the experiment each one belongs to. Click a knob to see what it does and which runs changed it.</p>')

# ---------- Q2 ----------
rep('<p>Look at the last group on the board: <b>where the network starts</b>. Most knobs describe the world or the training. The bias shift is different in kind. It reaches inside the network and moves one of the 8,708 learned numbers by hand, before training resumes. It does not change what the network is asked to do or how it is scored. It changes the network\'s starting position on the hill it is about to climb.</p>',
    '<p>Look at the last group on the board: <b>where the network starts</b>. Most knobs describe the world the fly lives in or the way training is run. The bias shift is a different kind of thing. It reaches inside the network and moves one of the 8,708 learned numbers by hand, before training resumes. It does not change what the network is asked to do, and it does not change how the network is scored. What it changes is the network\'s starting position before training begins to move it. In the drawing below, the curved line is the loss curve from the training picture in question 1 (the "hill"), and the dot on it is the network\'s current set of parameter values (the "climber"). Training moves the climber downhill.</p>')
rep('<div class="eyebrow">Drawn · a knob on the world versus a nudge to the climber</div>',
    '<div class="eyebrow">Drawing: an ordinary knob changes the shape of the hill; the bias shift moves the climber instead</div>')
rep('<p>Why count it separately? Three reasons, and they matter for what you are allowed to conclude.</p>',
    '<p>Why count it separately from the other knobs? There are three reasons, and each one limits what we are allowed to conclude from the runs.</p>')
rep('<p><b>It is not a property of the task.</b> If someone reproduces our world and training, they will not rediscover the reset unless they also do the shift. So "the fly\'s reset emerges from this task" is not a claim we can make. What we can say is "the task rewards a reset once the gate can hear it."</p>',
    '<p><b>It is not a property of the task.</b> If someone else reproduces our world and our training exactly, they will not rediscover the reset unless they also perform the shift by hand. So we cannot claim that "the fly\'s reset emerges from this task on its own." What we can say is "once the erase gate is in a position where training can move it, the task rewards a reset."</p>')
rep('<p><b>It is a warm start with a hand on the scale.</b> Every shifted run began from the previous run\'s trained weights. The shift was applied to one number out of 8,708, the erase gate\'s bias, and then gradient descent took over. So the finding is real (the network chose to fire at food, not away from it), but the starting point was chosen by us.</p>',
    '<p><b>It is a warm start plus one adjustment made by hand.</b> A warm start means that a run begins from the previous run\'s trained weights instead of from random ones. Every shifted run was a warm start. On top of that, we changed one number out of the 8,708, the erase gate\'s bias, by hand, and only then let gradient descent take over. So the finding is real: the network itself chose to fire the gate at food rather than away from food. But the starting point from which it made that choice was chosen by us.</p>')
rep('<p><b>It is repeatable, which makes it honest.</b> We did the same move five times (runs 7B, 10, 12, 14, 16) and wrote the prediction down each time. That turned a one-off intervention into a measured series: food-to-away ratios of 3, 7, 20, 33, 53. Question 3 shows why the move works at all.</p>',
    '<p><b>It was repeated, which turns it from a one-off into a measured series.</b> We made the same move five times (runs 7B, 10, 12, 14 and 16), and before each run we wrote down what we predicted would happen. Because the move was repeated, we can report the outcome as a series of measurements rather than a single event: the ratio of erasing at food to erasing away from food went 3, then 7, then 20, then 33, then 53. Question 3 explains why the move works at all.</p>')

# ---------- Q3 ----------
rep('It is a <span class="term" title="A function whose output is not simply proportional to its input: doubling the input does not double the output. Every squashing function is nonlinear">nonlinearity</span>: its output is not proportional to its input. And that is the whole story of the deaf gate. Drag the bias.</p>',
    'It is a <span class="term" title="A function whose output is not simply proportional to its input: doubling the input does not double the output. Every squashing function is nonlinear">nonlinearity</span>: its output is not proportional to its input. That squashing is the reason the gate was "deaf" to training, and the drawing below shows how. Drag the bias slider and watch the dot move along the curve.</p>')
rep('<div class="eyebrow">Drawn · the S curve, and how much a nudge moves it</div>',
    '<div class="eyebrow">Drawing: the S-shaped sigmoid curve, and how far one training nudge moves the gate at each resting position</div>')
rep('<small>The raw number z when no neuron is saying anything. Training moves it; the shift moved it by hand.</small>',
    '<small>The raw number z when no neuron is pushing on the gate. Training moves this number slowly; the bias shift moved it by hand.</small>')
rep('<small>How hard the gradient pushes on z. The same push moves the gate very differently depending on where it rests.</small>',
    '<small>How hard one training step pushes on z. The same push moves the gate\'s output by very different amounts depending on where the gate rests.</small>')
rep('<div class="how"><b>How to read it.</b> The curve is the gate\'s output for every possible raw input. The dot is where the gate rests. The short bar under the dot is how far one training nudge moves the output: it is the nudge times the curve\'s <span class="term" title="slope: how steep the curve is at that point, which is exactly how much the output changes for a small change in the input">slope</span> there. At −5 the slope is 0.007, so a nudge of 1 moves the gate by seven thousandths. At 0 the slope is 0.25, thirty-five times more.</div>',
    '<div class="how"><b>How to read it.</b> Across the bottom is the raw input z, which can be any number. Up the side is the gate\'s output, which is always between 0 and 1. The curve shows the output for every possible raw input. The dot marks where the gate rests when no neuron is pushing on it, which is set by the bias slider. The short bar under the dot shows how far one training nudge would move the gate\'s output from that resting position. Its length is the size of the nudge multiplied by the curve\'s <span class="term" title="slope: how steep the curve is at that point, which is exactly how much the output changes for a small change in the input">slope</span> at the dot. At z = −5 the slope is 0.007, so a nudge of 1 moves the gate by only seven thousandths. At z = 0 the slope is 0.25, which is thirty-five times larger, so the same nudge moves the gate thirty-five times as far. The buttons under the chart move the dot to each resting position the campaign actually used.</div>')
rep('<td>where the erase gate started: nearly shut, nearly deaf</td>',
    '<td>where the erase gate started: the gate is nearly shut, and the slope is so small that training can barely move it</td>')
rep('<td>after the first shift: ten times louder</td>',
    '<td>after the first shift: the slope is ten times larger, so each training step has ten times the effect</td>')
rep('<td>the loudest point on the curve</td>',
    '<td>the steepest point on the curve, where each training step has the largest effect</td>')
rep('<td>deaf again, at the top</td>',
    '<td>nearly flat again, at the top: the gate is almost fully open and training can barely move it</td>')
rep('<p style="font-size:15px"><b>Why the slope multiplies the nudge.</b> Training wants to change the gate\'s output. It can only change the raw z (through the bias and W_out). A small change in z changes the output by slope × that change: that is what slope means. So every gradient that reaches the gate is multiplied by the slope on its way to the bias. At −5 the multiplier is 0.0066. A push that would have moved the gate by 0.1 at z = 0 moves it by 0.0026 at z = −5.</p>',
    '<p style="font-size:15px"><b>Why the slope multiplies the nudge.</b> Training wants to change the gate\'s output. But it cannot touch the output directly; it can only change the raw number z, through the bias and through W_out. When z changes by a small amount, the output changes by the slope multiplied by that amount. That is what "slope" means: how much the output moves for each unit the input moves. So every training signal that reaches the gate is multiplied by the slope on its way to the bias. At z = −5 the multiplier is 0.0066. A push that would have moved the gate by 0.1 if the gate were resting at z = 0 moves it by only 0.0026 when the gate is resting at z = −5.</p>')
rep('<p>We started the erase gate at −5 on purpose, the way people start the "forget gate" of an LSTM mostly closed: if the network erased freely from the first iteration, the tallies could never build up and nothing would be learned. That worked. The cost was that the gate sat on the flat part of the S, where <span class="term" title="gradient descent: the training method. Compute which direction each number should move to lower the loss, then move a small step that way">gradient descent</span> could barely move it. Runs 2, 5 and 7 pushed on the gate with penalties of 0.5 and 20 and got nothing, because every push was multiplied by 0.007 before it reached the bias.</p>',
    '<p>We started the erase gate at −5 on purpose. This is the same precaution people take with the "forget gate" of an LSTM, which they usually start mostly closed. The worry is this: if the network erased freely from the very first training iteration, the tallies could never build up, and with nothing to build on nothing would be learned. The precaution worked, and the tallies did build up. The cost was that the gate sat on the flat part of the S curve, where <span class="term" title="gradient descent: the training method. Compute which direction each number should move to lower the loss, then move a small step that way">gradient descent</span> could barely move it. Runs 2, 5 and 7 pushed on the gate with penalties of 0.5 and 20 and got no movement, because every push was multiplied by 0.007 before it reached the bias.</p>')
rep('<p>The bias shift lifts the dot up the curve. At −2.5 the slope is 0.07, ten times louder; at 0 it is 0.25. Once there, the same gradients that had been ignored started to work: the network reduced erasing away from food (which costs distance) and increased it at food (which cleans the board for the next trip). Each later shift moved the rest position higher again, and each time training settled it a bit lower than where we put it, at a spot where erase at food is large and erase away is near 0.01. Run 19\'s trained bias is +1.86: the gate now rests at 0.87 open, and the neurons that read the food input push it down hard whenever the fly is not at food.</p>',
    '<p>The bias shift lifts the dot up the curve. At −2.5 the slope is 0.07, ten times larger than at −5; at 0 it is 0.25. Once the gate was on a steeper part of the curve, the same training signals that had been having no effect started to work. The network reduced erasing away from food, because erasing there loses part of the distance count, and it increased erasing at food, because that clears the board for the next trip. Each later shift moved the resting position higher again. Each time, training then settled the gate a little lower than where we had put it, at a spot where erasing at food is large and erasing away from food is near 0.01. Run 19\'s trained bias is +1.86. That means the gate now rests at 0.87 open, and the neurons that read the food input push it down hard whenever the fly is not at food.</p>')
rep('<div class="eyebrow">Real · erase per tick at food versus away, every run</div>',
    '<div class="eyebrow">Real data: erase per tick while at food and while away from food, for every run</div>')
rep('<div class="how"><b>How to read it.</b> Each run is a pair of bars on a <span class="term" title="log scale: each step up the axis multiplies by ten instead of adding a fixed amount, so 0.001, 0.01, 0.1 and 1 are evenly spaced">log scale</span>: coral is erase per tick at food, grey is away from food. Before run 7B the two are equal or the food one is lower (a fade). From 7B on, the food bar climbs shift by shift while the away bar stays put near 0.01.</div>',
    '<div class="how"><b>How to read it.</b> Each run gets a pair of bars. The coral bar is the average erase gate value per tick while the fly stands at food. The grey bar is the average erase gate value per tick everywhere else. The vertical axis is a <span class="term" title="log scale: each step up the axis multiplies by ten instead of adding a fixed amount, so 0.001, 0.01, 0.1 and 1 are evenly spaced">log scale</span>, which means each step up the axis multiplies the value by ten; this is used because the values range from below 0.001 to nearly 1, and on an ordinary scale the small ones would be invisible. What to look for: before run 7B, the two bars in each pair are about equal, or the coral bar is lower, which means the gate erases a little all the time and does not prefer food (a fade). From run 7B onward, the coral bar climbs with each shift while the grey bar stays put near 0.01. That is the reset appearing, one shift at a time.</div>')

# ---------- Q4 ----------
rep('<div class="eyebrow">Drawn · one connection under each rule while the fly walks the same heading</div>',
    '<div class="eyebrow">Drawing: one connection under each rule, while the fly walks in the same direction for many ticks</div>')
rep('<div class="how"><b>How to read it.</b> The fly holds one heading, so the same two neurons fire together tick after tick. Under Hebb the connection grows every tick: that is what a tally needs, count the steps. Under delta the connection grows only until it predicts the pattern, then flattens: that is what a memory of "what usually follows what" needs, but it is exactly wrong for counting. Twenty steps and sixty steps leave the same connection.</div>',
    '<div class="how"><b>How to read it.</b> Across the bottom is time in ticks. Up the side is the strength of one connection. The fly holds one heading for the whole time, so the same two neurons fire together tick after tick. The teal line is the connection under the Hebb rule: it grows on every tick, until it reaches the coral line, which is the ±1 lid. This is what a tally needs, because a tally has to keep counting the steps for as long as the fly keeps walking. The blue line is the same connection under the delta rule: it grows only until it can predict the pattern, and then it flattens out. That is what a memory of "what usually follows what" needs, because once the pattern is learned there is nothing more to learn. But it is exactly the wrong behaviour for counting: after the line flattens, twenty steps and sixty steps leave the connection at the same value, so the count is lost. Move the "ticks walking" slider to see this.</div>')
rep('<p>What happened: run 15 (cold start, rule swapped, nothing else changed) never formed a memory at all; the F-versus-no-F gap stayed at zero for 800 iterations and the write strength never moved. Run 18 (warm start from run 14\'s working Hebb tally) lost its memory within 100 iterations of the rule swap. The drawing shows why. This task is a counter. A rule that stops writing when it can predict the input stops counting exactly when the count matters. The negative result is clean and it is in both forms, but it is about this task, not about the delta rule in general: on a "what follows what" task the outcome would likely flip.</p>',
    '<p>What happened: run 15 (a cold start, with the rule swapped and nothing else changed) never formed a memory at all; the gap between the score with F and the score without F stayed at zero for 800 iterations, and the write strength never moved. Run 18 (a warm start from run 14\'s working Hebb tally) lost its memory within 100 iterations of the rule swap. The drawing above shows why. This task needs a counter. A rule that stops writing as soon as it can predict its input stops counting at exactly the moment the count matters. The negative result is clear, and it appeared in both forms of the test, the cold start and the warm start. But it is a result about this task, not about the delta rule in general. On a task that asks "what usually follows what", the outcome would very likely be the other way round.</p>')

# ---------- Q5 ----------
rep('<div class="eyebrow">Drawn · two kinds of comparison</div>',
    '<div class="eyebrow">Drawing: the two kinds of comparison used in the campaign</div>')
rep('Your worry applies to comparison 1: brain B was never trained to live without F, so of course it fails. That is the point of an</text>',
    'Your worry applies to comparison 1: brain B was never trained to live without F, so of course it fails. That is what an</text>')
rep('<tspan class="term">ablation</tspan>: remove a part and see what breaks. It locates the memory. It does not rank two designs. Comparison 2 does that, and it has its own caveats.</text>',
    '<tspan class="term">ablation</tspan> is for: remove one part and see what breaks. It shows where the memory is kept. It does not say which design is better; comparison 2 does that, with its own caveats.</text>')
rep('<p><b>So how should you think about A versus B?</b> As a locator, not a contest. When A homes and B walks randomly, we learn that the thing A uses to home lives in F and not in the neurons\' activity. That is a real fact about the trained brain, and it is the fact the roadmap called "memory in the synapses." It would be unfair only if we said "so fast weights beat activity," which the ablation cannot say.</p>',
    '<p><b>So how should you think about A versus B?</b> Think of it as a way of finding out where the memory is kept, rather than as a contest between two designs. When brain A homes and brain B walks randomly, we learn that whatever brain A uses to find home is stored in F and not in the neurons\' activity. That is a real fact about the trained brain, and it is the fact the roadmap called "memory in the synapses." The comparison would only be unfair if we used it to claim "fast weights are better than activity memory," and that is a claim the ablation cannot support.</p>')
rep('<p><b>The contest is the rival, run 20.</b> Same 64 neurons, same inputs, same training recipe as run 3, same seed, with the plastic part switched off before training. It never learned to home even at 10 seconds. That is evidence that, for this network and this recipe, an activity-only memory did not form. But a fair skeptic still gets three objections, and they are all right:</p>',
    '<p><b>The real contest between two designs is the rival, run 20.</b> It used the same 64 neurons, the same inputs, the same training recipe as run 3 and the same random seed, but with the plastic part switched off before training began. It never learned to home, even on 10-second trips. That is evidence that, for this network and this recipe, a memory held in the neurons\' activity alone did not form. But a fair skeptic still has three objections, and all three are valid:</p>')
rep('<p>One recipe and one seed is a single sample. The learning rate and the initial weights were tuned over twenty runs for the fast-weight version and zero runs for the rival. And 64 tanh neurons with all-to-all connections is a design where activity memories are hard to train by gradient descent anyway (the vanishing-gradient problem; LSTMs exist because of it), so the rival was fighting with one hand tied. A fair level 4 would give the rival several learning rates, a longer first stage, and ideally an LSTM-style cell that is built to hold activity. Until that is done, the honest sentence is: "the memory we trained lives in F, and a matched activity-only attempt did not learn." Not: "fast weights win."</p>',
    '<p>First, one recipe and one seed is a single sample, and a single sample can be unlucky. Second, the learning rate and the initial weights were tuned over twenty runs for the fast-weight version and over zero runs for the rival. Third, 64 tanh neurons with all-to-all connections is a design in which activity memories are known to be hard to train by gradient descent anyway. This is called the vanishing-gradient problem: the training signal shrinks each time it is passed back through one more tick, so a memory that must last many ticks receives almost no signal. LSTMs were invented to get around it. So the rival was at a disadvantage from the start. A fair level 4 would give the rival several learning rates to choose from, a longer first stage, and ideally an LSTM-style cell that is built to hold activity over time. Until that is done, the honest way to state the result is: "the memory we trained lives in F, and a matched attempt with activity memory only did not learn." It would be an overstatement to say "fast weights win."</p>')

# ---------- Q6 ----------
rep('<div class="eyebrow">Real · every run placed on the two numbers, with the rule drawn on</div>',
    '<div class="eyebrow">Real data: every run placed by its two erase numbers, with the labelling rule drawn on top</div>')
rep('<div class="how"><b>How to read it.</b> Across: erase away from food. Up: erase at food. Both on log scales. The diagonal is "equal at food and away"; anything on or below it is a fade or worse. The shaded corner is the rule\'s "reset" region. Watch the shifted runs (7B, 10, 12, 14, 16, 19) climb straight up along a nearly fixed away-value of about 0.01: the network sharpened the preference without ever changing how much it fades between food visits. You can move the thresholds with the sliders to see how sensitive the labels are.</div>',
    '<div class="how"><b>How to read it.</b> Across the bottom is the average erase per tick away from food. Up the side is the average erase per tick at food. Both axes are log scales, so each step along an axis multiplies the value by ten. Every run is one dot. The diagonal line marks "erase at food equals erase away from food"; a run on or below that line erases at least as much away from food as at food, which is a fade or worse. The shaded corner in the upper left is the region where the rule\'s two conditions are both met, so any run inside it is labelled "reset". What to look for: the shifted runs (7B, 10, 12, 14, 16 and 19) climb almost straight up, with the away-from-food value staying near 0.01 the whole time. That means the network sharpened its preference for erasing at food without ever changing how much it fades between food visits. The two sliders move the rule\'s thresholds, so you can check how much the labels depend on the exact numbers chosen.</div>')

# ---------- Q8 ----------
rep('<div class="eyebrow">Drawn · what a compass cell is</div>',
    '<div class="eyebrow">Drawing: the tuning curve of a compass cell, next to the tuning curve of a cell that is not tuned</div>')
rep('<div class="eyebrow">Real · all 64 tuning curves of run 19, strongest first</div>',
    '<div class="eyebrow">Real data: all 64 tuning curves from run 19, sorted with the strongest first</div>')
rep('<div class="how"><b>How to read it.</b> One small chart per neuron, headings east, north, west, south, east across the bottom, activity up. Teal curves are the 32 that pass the 0.25 test; grey are the rest. The number is the tuning strength. Notice that the tuned cells are not all copies: their peaks fall in different places. The histogram below counts them by preferred direction. A perfect compass would spread evenly around the circle; ours clusters (six cells prefer north-north-east, six prefer west-south-west, and two of the sixteen bins are empty), which is one of the ways it is still cruder than the fly.</div>',
    '<div class="how"><b>How to read it.</b> There is one small chart per neuron. Across the bottom of each chart is the fly\'s heading, going east, north, west, south and back to east. Up the side is the neuron\'s average activity at that heading. Teal curves belong to the 32 neurons whose tuning strength passes the 0.25 cutoff, so they count as compass cells. Grey curves belong to the rest. The number in the corner of each chart is that neuron\'s tuning strength. Notice that the tuned cells are not copies of one another: their peaks fall at different headings. The bar chart below the grid counts how many compass cells prefer each of the sixteen directions. A perfect compass would have its cells spread evenly around the circle. Ours are bunched: six cells prefer north-north-east, six prefer west-south-west, and two of the sixteen direction bins have no cells at all. This bunching is one of the ways our compass is still cruder than the fly\'s.</div>')
rep('<div class="eyebrow">Drawn · the wiring that makes a gate follow one input</div>',
    '<div class="eyebrow">Drawing: the wiring path that lets a gate follow one input</div>')
rep('<div class="eyebrow">Real · the eight neurons that drive each gate hardest, and what they listen to</div>',
    '<div class="eyebrow">Real data: the eight neurons that push each gate hardest, and how strongly each of them listens to the relevant input</div>')
rep('<div class="how"><b>How to read it.</b> Left, the write gate: for each of its eight strongest driver neurons, the pale bar is the neuron\'s weight from the speed wire and the dark bar is its weight into the gate. The dot is their product: positive means "faster, write more." Seven of eight products are positive. Right, the same for the erase gate against the food wire: positive means "at food, erase more." Five of eight are positive and the strongest driver, neuron 40, is strongly positive. This is the wiring behind the numbers in the leaderboard: write-versus-speed correlation +0.69, erase at food 0.38 versus 0.008 away.</div>',
    '<div class="how"><b>How to read it.</b> The left chart is about the write gate. It shows the eight neurons that push the write gate hardest. For each neuron there are two bars and a dot. The pale bar is that neuron\'s weight from the speed wire (how strongly it listens to speed). The dark bar is its weight into the write gate (how strongly it pushes the gate). The dot is the product of the two bars. A positive product means "when the fly goes faster, this neuron makes the gate write more." Seven of the eight products are positive. The right chart shows the same thing for the erase gate, but with the food wire in place of the speed wire, so a positive product there means "when the fly is at food, this neuron makes the gate erase more." Five of the eight products are positive, and the strongest driver, neuron 40, is strongly positive. These charts show the wiring that produces the numbers on the leaderboard: the correlation between the write gate and speed is +0.69, and the erase gate averages 0.38 at food against 0.008 away from food.</div>')
rep('<div class="eyebrow">Real · the twelve strongest fast weights across the two-trip test</div>',
    '<div class="eyebrow">Real data: the twelve strongest fast weights, followed through the whole two-trip test</div>')
rep('<div class="how"><b>How to read it.</b> Each teal line is one fast weight over the full 90-second test (two trips). Shaded columns are food stands. The lines build during a wander, hold on the way home, and drop at the food stand: that drop is the erase gate firing at 0.38 per tick for forty ticks. The board is cleared for the next trip. Compare the drawn version of this in the Night Report\'s run cards.</div>',
    '<div class="how"><b>How to read it.</b> Across the bottom is time in seconds over the full 90-second test, which contains two trips. Up the side is the value of a fast weight, between −1 and +1, with the ±1 lid drawn as dashed coral lines. Each teal line follows one of the twelve strongest fast weights. The grey line is the fly\'s distance from home. The shaded columns are the periods when the fly stands at food. What to look for: the teal lines build up while the fly wanders out, hold roughly steady on the way home, and then drop sharply inside a shaded column. That drop is the erase gate firing at 0.38 per tick for forty ticks in a row, which clears the board so that the next trip starts fresh. The Night Report\'s run cards show a drawn version of this same picture, which you can compare with the real one here.</div>')
rep('<div class="eyebrow">Real · connections between the 32 compass cells, sorted by preferred direction</div>',
    '<div class="eyebrow">Real data: the connections between the 32 compass cells, sorted by preferred direction</div>')
rep('<div class="how"><b>How to read it.</b> Rows are receiving cells, columns are sending cells, both in order of preferred direction from east round to east. Red is a positive weight, blue negative. The bottom chart averages the weights by how far apart the two cells\' preferred directions are: a ring would show a positive hump at 0° and a negative dip at ±180°. Run 19\'s W shows only a faint version of this (mean weight ranges from −0.04 to +0.05), and A shows none. So our compass cells are real as tuning curves but are not wired as a ring. They do not need to be: the heading comes in on the input wires every tick, so the network never has to hold a heading by itself the way Peter\'s network did. This is the clearest difference between the two projects, and it is a difference in the task, not a failure.</div>',
    '<div class="how"><b>How to read it.</b> In the two square pictures, each row is a receiving cell and each column is a sending cell. Both rows and columns are in order of preferred direction, starting at east and going round the circle back to east. Red means a positive weight and blue means a negative weight. The chart underneath takes all those weights and averages them according to how far apart the two cells\' preferred directions are, from −180° to +180°. If the cells were wired as a ring, this chart would show a positive hump at 0° (cells that like the same direction excite each other) and a negative dip at ±180° (cells that like opposite directions quiet each other); the dashed blue line shows that ideal shape. Run 19\'s W (the black line) shows only a faint version of it, with the mean weight ranging from −0.04 to +0.05, and A (the teal line) shows none at all. So our compass cells are real in the sense that they have clear tuning curves, but they are not wired together as a ring. They do not need to be. Our fly is handed its heading on the input wires every tick, so the network never has to hold on to a heading by itself, which is what Peter\'s network had to do. This is the clearest difference between the two projects. It comes from a difference between the two tasks, so it should not be read as a failure of our network.</div>')

# ---------- Q9 ----------
rep('then train everything by ordinary gradient descent. Toggle the rules to see the family tree our network sits in.</p>',
    'then train everything by ordinary gradient descent. Press the buttons below to step through the family of rules, from a plain network up to ours, and see where our network sits in it.</p>')
rep('<tr><td>the point of the paper</td><td>neuromodulation helps on RL and language tasks</td><td>does a fly-like circuit emerge, and where does the memory live</td></tr>',
    '<tr><td>what the paper set out to show</td><td>neuromodulation helps on RL and language tasks</td><td>does a fly-like circuit emerge, and where does the memory live</td></tr>')
rep('<p>So FlyNet is "simple Backpropamine plus an erase gate," applied to a navigation task and then dissected. Nothing about our learning rule is new; what is ours is the question (do the three fly motifs appear), the world, and the analysis. Peter\'s note says the same thing in the field\'s words. It also places delta and the newer sequence models (Gated DeltaNet, Titans) as the next rungs of the same ladder.</p>',
    '<p>So FlyNet is "simple Backpropamine plus an erase gate," applied to a navigation task and then taken apart to see how it works. Nothing about our learning rule is new. What is ours is the question we ask (do the three fly motifs appear?), the world the fly lives in, and the analysis of the trained network. Peter\'s note says the same thing in the words the field uses. His note also places the delta rule and the newer sequence models (Gated DeltaNet, Titans) as the next steps along the same line of ideas.</p>')

# ---------- Q10 ----------
rep('<div class="eyebrow">Drawn · their task and what emerged</div>',
    '<div class="eyebrow">Drawing: the task in Peter\'s paper, and the ring of cells that emerged from training on it</div>')
rep('<p>One more parallel that is worth saying out loud. Their claim was not "this network is the fly." It was that the fly\'s design is what optimisation finds when the task is this task, and that anatomy can be predicted from function. Our version of that claim, smaller and with its caveats attached in question 2, is: given a homing task with a place to reset, gradient descent will build a compass, a speed-weighted tally and a wipe, provided the gate that does the wiping can hear its gradients.</p>',
    '<p>One more parallel is worth saying out loud. Their claim was not "this network is the fly." Their claim was that the fly\'s design is what optimisation arrives at when the task is this task, and therefore that you can predict anatomy from function. Our version of that claim is smaller, and it carries the caveats listed in question 2. It is this: given a homing task with a place to reset, gradient descent will build a compass, a speed-weighted tally and a wipe at food, provided that the gate which does the wiping is resting where training can move it.</p>')

# ---------- Q11 ----------
rep('<p>No. The rule runs every tick of every trip, out and back, with no switch. That is the point of a home vector: walking away adds to it, walking home subtracts from it, and it reads zero when you are back. Whether the network actually does the subtraction is a question the data can answer, so here is the same run 19 trip with the average size of the twelve traced fast weights marked at a few moments.</p>',
    '<p>No. The rule runs on every tick of every trip, on the way out and on the way back, and there is no switch that turns it off. That is what a home vector is: walking away from home adds to it, walking towards home subtracts from it, and it reads zero when you are back. Whether the network actually does the subtracting on the way back is a question the data can answer, so here is the same run 19 trip as before, with the average size of the twelve traced fast weights written down at a few moments.</p>')
rep('<div class="eyebrow">Real · run 19, one exam trip, the tally rising on the way out and falling on the way back</div>',
    '<div class="eyebrow">Real data: one exam trip from run 19, showing the tally rising on the way out and falling on the way back</div>')
rep('<div class="how"><b>How to read it.</b> Outbound, the size of the fast weights climbs with distance. Inbound, it falls as the fly closes on home. It does not reach zero, because on this trip the fly never quite got there (its closest approach was 1.5, and then it circled), and every circle adds a little back in. So: two-way counting, confirmed on the real trace, with the return leg less clean than the outbound one. Which is another way of saying what the stress test says.</div>',
    '<div class="how"><b>How to read it.</b> The first column is time in seconds, the second is the fly\'s distance from home, and the third is the average size (ignoring sign) of the twelve traced fast weights at that moment. On the way out, the size of the fast weights climbs as the distance climbs. On the way back, it falls as the fly gets closer to home. It does not fall all the way to zero, because on this trip the fly never quite reached home: its closest approach was a distance of 1.5, and after that it circled, and every circle adds a little back into the tally. So the table confirms two-way counting on a real trace, with the return leg less clean than the outbound leg. That is the same conclusion the stress test reached by a different route.</div>')
rep('<p>It cannot, and I muddled two scales on that page. In the network every one of the 4,096 fast weights is clamped to ±1, full stop. The "lid" slider',
    '<p>It cannot, and I muddled two different scales on that page. In the network, every one of the 4,096 fast weights is clamped to lie between −1 and +1, with no exceptions. The "lid" slider')

# ---------- EXPL ----------
rep("W:'<b>W, the slow table, 64 × 64.</b> The permanent strength of every connection from neuron j to neuron i. Trained by gradient descent across thousands of episodes, then frozen. This is the rulebook.',",
    "W:'<b>W, the slow table, 64 × 64.</b> The permanent strength of every connection from neuron j to neuron i. It is trained by gradient descent across thousands of episodes and then frozen. Because it never changes during a trip, it holds the network\\'s long-term habits: the parts of its behaviour that are the same on every trip.',")
rep("win:'<b>W_in, 4 × 64 weights plus 64 biases.</b> Each input wire connects to every neuron with its own strength. Trained, then frozen: part of the slow weights.',",
    "win:'<b>W_in, 4 × 64 weights plus 64 biases.</b> Each of the four input wires connects to every one of the 64 neurons, and each of those connections has its own strength. These strengths are trained and then frozen, so they count as part of the slow weights.',")
rep("ws:'<b>ws, the write strength.</b> One trained number that scales every write into F. Level 1 had this as a dial; here it is learned. Run 19 settled it at 0.074.',",
    "ws:'<b>ws, the write strength.</b> A single trained number that multiplies every write into F. In level 1 this was a dial you could turn by hand; here training sets it. Run 19 settled it at 0.074.',")
rep("out1:'<b>Write gate.</b> A sigmoid, 0 to 1. Multiplies the write into F this tick. If it follows speed, the tally counts distance rather than time.',",
    "out1:'<b>Write gate.</b> A number between 0 and 1, produced by a sigmoid. It multiplies the amount written into F this tick. If the gate opens more when the fly moves faster, then fast steps are recorded more strongly than slow ones, and the tally counts distance walked rather than time spent.',")
rep("out2:'<b>Erase gate.</b> A sigmoid, 0 to 1. The fraction of F that is wiped this tick. Near 0.01 it is a slow fade; near 1 at food and near 0 elsewhere it is the fly\\'s reset.'};",
    "out2:'<b>Erase gate.</b> A number between 0 and 1, produced by a sigmoid. It is the fraction of every cell of F that is removed this tick. If it stays near 0.01 everywhere, the memory slowly fades. If it is near 1 at food and near 0 everywhere else, it acts as the fly\\'s reset: the board is wiped at food and kept intact the rest of the time.'};")

# ---------- WHY ----------
rep("const WHY={run1:'The plan\\'s first run. Nothing to look at yet, so no knob: establish the baseline and see what gradient descent does on its own.',",
    "const WHY={run1:'The plan\\'s first run. There was nothing to look at yet, so no knob was turned. The purpose was to establish a baseline and see what gradient descent does when left on its own.',")
rep("run2:'Run 1 found a slow fade instead of a reset. The simplest lever on erasing is the penalty for erasing away from food. Multiply it by ten.',",
    "run2:'Run 1 produced a slow fade instead of a reset. The simplest thing we can change that bears on erasing is the penalty charged for erasing away from food. So this run multiplies that penalty by ten.',")
rep("run3:'Run 2 showed a penalty can shut the gate rather than aim it. The other way to teach a reset is more evidence: more ticks at the food. Stand for 2 s instead of 0.5 s.',",
    "run3:'Run 2 showed that a penalty can shut the gate completely rather than teach it when to fire. The other way to teach a reset is to give the network more evidence: more ticks spent at the food. So this run has the fly stand at food for 2 seconds instead of 0.5 seconds.',")
rep("run4:'Run 3 homed at 20 s but still faded. If the board carries five trips instead of two, leftovers hurt more, so the erase gate has a stronger reason to fire at food. Warm start from run 3\\'s best.',",
    "run4:'Run 3 learned to home on 20-second trips but its memory still faded rather than reset. If the board has to carry five trips in a row instead of two, then leftovers from an old trip do more damage, and the erase gate has a stronger reason to fire at food. This run is a warm start from run 3\\'s best weights.',")
rep("run5:'Run 2\\'s penalty had been tried cold and died. Try it warm, on a network that already homes, so the penalty cannot kill the memory before it forms.',",
    "run5:'Run 2\\'s penalty had been tried from a cold start and the network died. This run tries the same penalty from a warm start, on a network that already knows how to home, so that the penalty cannot kill the memory before the memory has formed.',")
rep("run6:'Two runs on the erase gate had done nothing. Stop and earn the 30-second stage, since 30 s scores were being reported on networks that never trained there. Hygiene: cosine decay, after run 5\\'s collapse.',",
    "run6:'Two runs aimed at the erase gate had done nothing. So this run stops working on the gate and instead trains properly at the 30-second stage, because until now 30-second scores were being reported for networks that had never trained on 30-second trips. It also adds a piece of good practice after run 5\\'s collapse: cosine decay, which means the learning rate is gradually lowered over the run so that late steps are small.',")
rep("run6B:'Run 6 collapsed at iteration 500 even with decay. Same experiment, a third of the step size.',",
    "run6B:'Run 6 collapsed at iteration 500 even with the decay in place. This run repeats the same experiment with a step size (learning rate) one third as large.',")
rep("run7:'0.5 was a rounding error next to a loss of 2. Make the penalty real: 20. If the gate still does not move, the problem is not the price.',",
    "run7:'A penalty of 0.5 is tiny next to a loss of about 2, so it was never going to matter. This run makes the penalty large enough to matter: 20. The reasoning was that if the gate still does not move under a penalty of 20, the problem is not that the penalty is too small; something else is stopping the gate from moving.',")
rep("run7B:'Run 7 gave the diagnosis: the sigmoid at −5 has slope 0.007. Test it directly: lift the bias by 2.5 and keep everything else, including the penalty.',",
    "run7B:'Run 7 gave the diagnosis: with the gate parked at −5 on its sigmoid curve, the slope there is 0.007, so training can barely move it. This run tests that diagnosis directly by lifting the bias by 2.5 and keeping everything else the same, including the penalty.',")
rep("run8:'7B made the gate lean toward food (ratio 3). Before pushing harder, check whether time alone sharpens it: continue with nothing changed.',",
    "run8:'Run 7B made the gate erase three times as much at food as away from it (a ratio of 3). Before pushing harder, this run checks whether simply training for longer sharpens that preference on its own. Nothing is changed; training just continues.',")
rep("run8B:'Run 8 stalled at ratio 1.5 to 3. Now that the gate can hear, retry the run 3 idea: more food ticks (4 s) should mean more gradient for erasing at food.',",
    "run8B:'Run 8 stalled at a ratio between 1.5 and 3. Now that the gate is in a position where training can move it, this run retries the idea from run 3: more ticks at food (4 seconds) should give training more evidence in favour of erasing at food.',")
rep("run9:'Everything so far was warm starts. The decisive version: a cold start whose gate can hear from iteration 1. Does the reset emerge on its own?',",
    "run9:'Every shifted run so far had been a warm start. This run is the decisive version of the test: a cold start (random weights) whose gate is placed where training can move it from the very first iteration. The question is whether the reset emerges on its own when the gate can be trained from the beginning.',")
rep("run9B:'Run 9\\'s penalty of 20 shut the gate before any memory existed. Cut it to 2 so the gate stays audible while the tally forms.',",
    "run9B:'In run 9, the penalty of 20 shut the gate before any memory had formed. This run cuts the penalty to 2, so that the gate stays in a trainable position while the tally is still forming.',")
rep("run10:'The first shift lifted the ratio to 3, then training settled. Do the same move again (+1.5) and see if the preference ratchets or returns to 3.',",
    "run10:'The first shift lifted the food-to-away ratio to 3, and then training settled there. This run makes the same move again (a further +1.5 on the bias) to find out whether the preference climbs another step or falls back to 3.',")
rep("run11:'Every finding is from seed 0. Replicate run 3\\'s recipe from a different random start to see if compass cells and speed-following writing are robust.',",
    "run11:'Every finding so far comes from a single random seed, seed 0. This run repeats run 3\\'s recipe from a different random starting point, to see whether the compass cells and the speed-following write gate appear again or were luck.',")
rep("run11B:'The stop rule ended run 11 across a promotion, which was unfair. Continue it with the rule suspended.',",
    "run11B:'The automatic stop rule ended run 11 just as it was being promoted to a longer trip length, which was unfair to it. This run continues run 11 with the stop rule switched off.',")
rep("run12:'Ratio went 3 then 7. A third shift tests whether the ratchet keeps going.',",
    "run12:'The ratio went from 3 to 7 after the second shift. This run makes a third shift to test whether each shift keeps adding to the preference.',")
rep("run13:'A different lever entirely: a world where time and distance disagree (slow half, fast half). If writing must follow speed to home, the write gate should sharpen.',",
    "run13:'A different kind of change altogether: a world in which time and distance disagree, because the fly walks slowly for one half of the trip and fast for the other half. In such a world, the only way to home is to make the write gate follow speed, so the prediction is that the write gate\\'s link to speed should sharpen.',")
rep("run14:'Ratio 3, 7, 20. A fourth shift: does it reach a full wipe?',",
    "run14:'The ratio has gone 3, 7, 20. This run makes a fourth shift and asks whether the gate reaches a full wipe at food.',")
rep("run15:'Peter\\'s note proposed the delta rule. Cold start, run 3\\'s recipe, only the rule changed. Prediction on record from Peter.',",
    "run15:'Peter\\'s note proposed the delta rule. This run is a cold start using run 3\\'s recipe with only the learning rule changed. Peter\\'s prediction was written down before the run.',")
rep("run16:'Ratio 3, 7, 20, 33 and peaks near 0.9. Fifth shift: is the wipe complete?',",
    "run16:'The ratio has gone 3, 7, 20, 33, and the gate now peaks near 0.9 at food. This run makes a fifth shift and asks whether the wipe becomes complete.',")
rep("run17:'The best score line (run 13) had only ever trained at 3e-4. Polish at a tenth of that, nothing else changed.',",
    "run17:'The best-scoring line of runs (run 13) had only ever been trained with a learning rate of 3e-4, that is, 0.0003. This run continues it at one tenth of that rate, with nothing else changed, to polish the result with smaller steps.',")
rep("run18:'Run 15 failed cold. The fair second form: switch the rule on a working tally (run 14) so the rule is the only difference.',",
    "run18:'Run 15 failed from a cold start. The fair second form of the test is to switch the rule on a network that already has a working tally (run 14), so that the rule is the only thing that differs.',")
rep("run19:'Two lines existed: the best score (legs world, run 13) and the best reset (run 14). Apply the legs world to the reset network to see if the ingredients stack.',",
    "run19:'Two separate lines of runs existed: the one with the best score (the legs world, run 13) and the one with the best reset (run 14). This run applies the legs world to the best-reset network, to see whether the two improvements can be combined.',")
rep("run20:'The level 4 comparison the plan was built for: the same network with fast weights disabled, trained with run 3\\'s recipe.'};",
    "run20:'This is the comparison the whole plan was built for, and it belongs to level 4: the same network with the fast weights switched off, trained with run 3\\'s recipe.'};")

# ---------- RULES ----------
rep("A plain recurrent network. Every connection has one strength, W, that never changes while the network runs. Memory can only live in the neurons\\' activity, echoing round the loop. This is the rival, run 20, in spirit.</p>'],",
    "A plain recurrent network. Every connection has one strength, W, and that strength never changes while the network runs. So the only place a memory can live is in the neurons\\' activity, passed round and round the loop from one tick to the next. Run 20, the rival, is essentially this kind of network.</p>'],")
rep("Both are learned by backprop across episodes; Hebb itself is not learned, it happens.</p>'],",
    "Both of those are learned by backprop across episodes. Hebb itself is not set by training; it is produced by the network\\'s own activity while it runs, and it starts again from zero in each episode.</p>'],")
rep("Backpropamine, simple form. The fixed η becomes M(t), a number the network outputs every tick. Now the network decides when to be plastic. M(t) can be negative, which un-writes. This is the dopamine analogy: a global \"learn now\" signal under the brain\\'s own control.</p>'],",
    "Backpropamine, simple form. The fixed writing rate η is replaced by M(t), a number the network itself outputs on every tick. So the network now decides, moment by moment, how much its connections should change. M(t) can also be negative, in which case it removes what was written earlier. This is where the dopamine analogy comes from: in the brain, dopamine is a chemical signal, sent to many neurons at once, that tells them to strengthen their recent connections. M(t) plays the same role here, a single \"learn now\" signal that the network controls itself.</p>'],")
rep("Only when M(t) fires does the trace become a real change. So a reward signal can reach back about a second and stamp in what led to it, which is what dopamine does in real synapses.</p>'],",
    "Only when M(t) fires does the trace turn into a real change in the connection. This means a reward signal can arrive up to about a second late and still strengthen the connections that were active just before it, which is what dopamine is believed to do at real synapses.</p>'],")
rep("FlyNet. Take the simple Backpropamine rule, call α \"A\" and Hebb \"F\", make M(t) = ws × write(t), and add a second self-produced gate, erase(t), that multiplies the old F. That erase gate is the whole difference, and it exists because the fly needs to wipe its tally at food. Everything else is inherited.</p>']];",
    "FlyNet. Start from the simple Backpropamine rule. Rename α to \"A\" and Hebb to \"F\". Set M(t) equal to ws × write(t), a trained constant times a gate the network produces. Then add a second gate that the network also produces, erase(t), which multiplies the old F on every tick. The erase gate is the only real difference between the two rules, and it was added because the fly needs to wipe its tally when it reaches food. Every other part of the rule is inherited from Backpropamine.</p>']];")

missing=[o for o,n in R if s.count(o)!=1]
if missing:
    for m in missing: print('NOT FOUND or NOT UNIQUE:',m[:100])
    sys.exit(1)
for o,n in R:
    s=s.replace(o,n)
assert "'''" not in ''.join(n for o,n in R)
open(P,'w').write(s)
print('applied',len(R),'replacements')
